apiVersion: v1
kind: Service
metadata:
  name: spring-boot-todo-service
spec:
  selector:
    app: spring-boot-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
